# Generated by Django 5.0.2 on 2024-02-15 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('state_name', models.CharField(verbose_name=200)),
                ('state_code', models.CharField(verbose_name=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_data', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Master',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Name', models.CharField(verbose_name=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(verbose_name=20)),
                ('phone', models.IntegerField()),
                ('city', models.CharField(verbose_name=200)),
                ('gender', models.CharField()),
                ('joining_data', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_data', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tickets.state_master')),
            ],
        ),
        migrations.CreateModel(
            name='Task_Master',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('task_id', models.CharField(verbose_name=200)),
                ('title', models.CharField(verbose_name=200)),
                ('description', models.TextField()),
                ('assign_date', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_data', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tickets.state_master')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tickets.user_master')),
            ],
        ),
    ]
